# Generated by Django 4.0.5 on 2022-06-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
    ]
